//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITechJumpAudit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITechJumpAudit()
        {
            this.ITechJumpAuditDetails = new HashSet<ITechJumpAuditDetail>();
        }
    
        public int AuditID { get; set; }
        public string UserId { get; set; }
        public string Origin { get; set; }
        public string EventType { get; set; }
        public string ErrorCode { get; set; }
        public string CommentShort { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public int SeverityCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITechJumpAuditDetail> ITechJumpAuditDetails { get; set; }
    }
}
