//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class iTechCards_Cash5
    {
        public int WID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserAlias { get; set; }
        public System.DateTime CDate { get; set; }
        public string CardGame { get; set; }
        public int CardGroup { get; set; }
        public int CardSlot { get; set; }
        public int Active { get; set; }
        public string CardName { get; set; }
        public int Num1 { get; set; }
        public int Num2 { get; set; }
        public int Num3 { get; set; }
        public int Num4 { get; set; }
        public int Num5 { get; set; }
        public int Multi { get; set; }
    }
}
