//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITechJumpAuditDetail
    {
        public int AuditDetailID { get; set; }
        public int RefAuditID { get; set; }
        public string Comment { get; set; }
        public string ErrorDesc { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
    
        public virtual ITechJumpAudit ITechJumpAudit { get; set; }
    }
}
