//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryDrawResultsMega
    {
        public int ResultID { get; set; }
        public int UserID { get; set; }
        public string UserAlias { get; set; }
        public string CardName { get; set; }
        public string GameName { get; set; }
        public int WID { get; set; }
        public System.DateTime DrawDate { get; set; }
        public byte Num1 { get; set; }
        public byte Num2 { get; set; }
        public byte Num3 { get; set; }
        public byte Num4 { get; set; }
        public byte Num5 { get; set; }
        public byte PNum { get; set; }
        public byte UNum1 { get; set; }
        public byte UNum2 { get; set; }
        public byte UNum3 { get; set; }
        public byte UNum4 { get; set; }
        public byte UNum5 { get; set; }
        public byte UPNum { get; set; }
        public bool Winner { get; set; }
        public byte RequestMatch { get; set; }
        public byte ActualMatch { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> EMailSent { get; set; }
    }
}
