//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class iTechWinnersTexa
    {
        public int WID { get; set; }
        public string Game { get; set; }
        public System.DateTime GDate { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string Year { get; set; }
        public string Num1 { get; set; }
        public string Num2 { get; set; }
        public string Num3 { get; set; }
        public string Num4 { get; set; }
        public string Num5 { get; set; }
        public string Num6 { get; set; }
        public string Multi { get; set; }
        public string FullPrize { get; set; }
        public string CashPrize { get; set; }
        public Nullable<int> SomeOneWin { get; set; }
    }
}
