//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        [Key]
        public string PlanCode { get; set; }
        public string PlanName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public string BillingPeriod { get; set; }
        public Nullable<int> TrialDays { get; set; }
        public Nullable<int> MaxUsers { get; set; }
        public Nullable<int> MinNumbers { get; set; }
        public Nullable<int> MaxNumbers { get; set; }
        public Nullable<int> TicketSets { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
