//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace EmpireOneRestAPIITJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        [Key]
        public int SubscriptionId { get; set; }
        public int UserId { get; set; }
        public string UserAlias { get; set; }
        public string PlanCode { get; set; }
        public string Status { get; set; }
        public bool AutoRenew { get; set; }
        public int Quantity { get; set; }
        public System.DateTime StartUtc { get; set; }
        public Nullable<System.DateTime> CurrentPeriodStartUtc { get; set; }
        public Nullable<System.DateTime> CurrentPeriodEndUtc { get; set; }
        public Nullable<System.DateTime> TrialEndUtc { get; set; }
        public Nullable<System.DateTime> CanceledAtUtc { get; set; }
        public Nullable<System.DateTime> EndedAtUtc { get; set; }
        public decimal PriceAtPurchase { get; set; }
        public string Currency { get; set; }
        public string ExternalProvider { get; set; }
        public string ExternalSubscriptionId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual User User { get; set; }
    }
}
